apiVersion: v1
kind: ConfigMap
metadata:
  name: physgrad-config
  namespace: physgrad
  labels:
    app: physgrad
data:
  # Physics simulation parameters
  PHYSICS_TIMESTEP: "0.001"
  MAX_PARTICLES: "10000000"
  CUDA_DEVICE_COUNT: "auto"

  # Performance settings
  THREADS_PER_BLOCK: "256"
  BLOCKS_PER_GRID: "auto"
  MEMORY_POOL_SIZE: "2GB"

  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  METRICS_ENABLED: "true"

  # Networking
  API_PORT: "8080"
  METRICS_PORT: "8081"
  HEALTH_PORT: "8082"

  # Storage paths
  DATA_PATH: "/app/data"
  RESULTS_PATH: "/app/results"
  LOGS_PATH: "/app/logs"