apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: physgrad-data-pvc
  namespace: physgrad
  labels:
    app: physgrad
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: physgrad-results-pvc
  namespace: physgrad
  labels:
    app: physgrad
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: standard