apiVersion: v1
kind: Service
metadata:
  name: physgrad-api
  namespace: physgrad
  labels:
    app: physgrad
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: api
  selector:
    app: physgrad
    component: compute

---
apiVersion: v1
kind: Service
metadata:
  name: physgrad-metrics
  namespace: physgrad
  labels:
    app: physgrad
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: metrics
  selector:
    app: physgrad
    component: compute

---
apiVersion: v1
kind: Service
metadata:
  name: physgrad-health
  namespace: physgrad
  labels:
    app: physgrad
    component: health
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: health
  selector:
    app: physgrad
    component: compute