name: PhysGrad CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  BUILD_TYPE: Release

jobs:
  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-11, g++-12]
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler }} cmake ninja-build
        sudo apt-get install -y libeigen3-dev

    - name: Build tests
      run: |
        g++ -std=c++20 -I. test_concepts_v2.cpp -o test_concepts_v2
        g++ -std=c++20 -I./src -I./external/eigen3 test_memory_minimal.cpp -o test_memory_minimal -O2

    - name: Run tests
      run: |
        chmod +x scripts/run_tests.sh
        ./scripts/run_tests.sh --category core
        ./scripts/run_tests.sh --category concepts

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Run static analysis
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 src/ || true
